
services:
  backend:
    build:
      context: ./PhotoServer
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./PhotoServer:/rails
      - /rails/tmp
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - db
    networks:
      - app_network
    
  db:
    image: mariadb:latest
    environment:
      # MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app_network

  frontend:
    build:
      context: ./front_end  # Points to your Vue.js project
      dockerfile: Dockerfile.dev
    volumes:
      - "./front_end:/app"
      - "/frontend/node_modules"  # Prevents syncing node_modules between host & container
    ports:
      - "5173:5173"  # Vue.js default port
    environment:
      - VITE_API_URL="http://backend:3000"  # Vue.js should use the backend service name
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  mariadb_data:
  rails_tmp:

networks:
  app_network:
    driver: bridge
